name: 'Install feelpp deb packages'
description: 'Install feelpp deb packages on a Debian or Ubuntu host'
branding:
  icon: 'archive'  
  color: 'purple'
inputs:
  dist:
    description: 'focal, jammy, bullseye, ...'
    required: false
    default: jammy
  flavor:
    description: 'distribution flavor: ubuntu, debian'
    required: false
    default: ubuntu
  version:
    description: 'packages version: latest or stable'
    required: false
    default: latest
  repo:
    description: 'feelpp deb repository'
    required: false
    default: http://apt.feelpp.org
  repo-name:
    description: 'name of the repository, the name will be used for a new file in the /etc/apt/sources.list.d directory, the .list suffix will be added to the name'
    required: false
    default: feelpp
  key:
    description: 'feelpp key'
    required: false
    default: http://apt.feelpp.org/apt.gpg
  install:
    description: "install feelpp packages"
    required: false
    default: 'libfeelpp1 libfeelpp-dev feelpp-tools'
runs:
  using: "composite"
  steps:
    - name: add feelpp apt key
      run: |
          set -x
          if [ "$(id --user)" -eq "0" ]; then
            sudocmd=""
          else
            sudocmd="sudo"
          fi
        
          $sudocmd apt update || true
          $sudocmd apt install -yq apt-transport-https ca-certificates gnupg software-properties-common wget
          wget -qO - http://apt.feelpp.org/apt.gpg | $sudocmd  apt-key add -
          
          if [ "${{ inputs.dist }}" == "bionic" -a "${{ inputs.flavor }}" == "ubuntu"]; then
            echo bionic
          fi
      shell: bash
    - name: add feelpp repo
      run: |
        set -x
        if [ "$(id --user)" -eq "0" ]; then
          sudocmd=""
        else
          sudocmd="sudo"
        fi
        
        $sudocmd add-apt-repository "deb http://apt.feelpp.org/${{ inputs.flavor }}/${{ inputs.dist }} ${{ inputs.dist }} ${{ inputs.version }}" 
        if [ "${{ inputs.dist }}" == "buster" -a "${{ inputs.flavor }}" == "debian" ]; then
             $sudocmd add-apt-repository "deb http://deb.debian.org/debian buster-backports main" 
        fi
        $sudocmd apt update || true
        if [ "${{ inputs.dist }}" == "buster" -a "${{ inputs.flavor }}" == "debian" ]; then
             $sudocmd apt install -yq  clang-8/buster-backports cmake/buster-backports
        fi
      shell: bash
    - name: install feelpp
      run: |
          if [ "$(id --user)" -eq "0" ]; then
            sudocmd=""
          else
            sudocmd="sudo"
          fi
            
          $sudocmd apt update 
          $sudocmd apt install --reinstall -yq ${{ inputs.install }}
      shell: bash
