name: 'Install feelpp deb packages'
description: 'Install feelpp deb packages on a Debian or Ubuntu host'
branding:
  icon: 'archive'  
  color: 'purple'
inputs:
  dist:
    description: 'ubuntu or debian'
    required: false
    default: ubuntu
  flavor:
    description: 'distribution flavor'
    required: false
    default: focal
  version:
    description: 'packages version: latest or stable'
    required: false
    default: latest
  repo:
    description: 'feelpp repository line as it appears in the sources.list'
    required: false
    default: deb https://dl.bintray.com/feelpp/${{ dist }} ${{ flavor }} ${{ version }}
  repo-name:
    description: 'name of the repository, the name will be used for a new file in the /etc/apt/sources.list.d directory, the .list suffix will be added to the name'
    required: false
    default: feelpp
  key:
    description: 'feelpp bintray key'
    required: false
    default: https://bintray.com/user/downloadSubjectPublicKey?username=bintray
  install:
    description: "install feelpp packages"
    required: false
    default: 'libfeelpp1 libfeelpp-dev feelpp-tools'
runs:
  using: "composite"
  steps:
    - name: add feelpp bintray key
      run: |
          if [ "$(id --user)" -eq "0" ]; then
            sudocmd=""
          else
            sudocmd="sudo"
          fi
        
          $sudocmd apt update || true
          $sudocmd apt-get install -yq apt-transport-https ca-certificates gnupg software-properties-common wget
          wget -qO - https://bintray.com/user/downloadSubjectPublicKey?username=bintray | $sudocmd  apt-key add -
          
          if [ "${{ flavor }}" -eq "bionic"]; then
            echo bionic
          fi
      shell: bash
    - name: add feelpp repo
      run: |
        if [ "$(id --user)" -eq "0" ]; then
          sudocmd=""
        else
          sudocmd="sudo"
        fi
        
        echo "${{ inputs.repo }}" | $sudocmd tee /etc/apt/sources.list.d/${{ inputs.repo-name }}.list
        if [ "${{ flavor }}" -eq "buster"]; then
             echo "deb http://deb.debian.org/debian buster-backports main" | $sudocmd  tee  /etc/apt/sources.list.d/${{ inputs.repo-name }}.list
        fi
        $sudocmd apt update || true
      shell: bash
    - name: install feelpp
      run: |
          if [ "$(id --user)" -eq "0" ]; then
            sudocmd=""
          else
            sudocmd="sudo"
          fi
            
          $sudocmd apt update 
          $sudocmd apt install --reinstall -yq ${{ inputs.install }}
      shell: bash
