name: 'Install feelpp deb packages'
description: 'Install feelpp deb packages on a Debian/Ubuntu host'
branding:
  icon: 'archive'  
  color: 'purple'
inputs:
  dist:
    description: 'ubuntu or debian'
    required: false
    default: ubuntu
  flavor:
    description: 'distribution flavor'
    required: false
    default: focal
  version:
    description: 'packages version: latest or stable'
    required: false
    default: latest
  repo:
    description: 'feelpp repository line as it appears in the sources.list'
    required: true
    default: deb https://dl.bintray.com/feelpp/ubuntu focal latest
  repo-name:
    description: 'name of the repository, the name will be used for a new file in the /etc/apt/sources.list.d directory, the .list suffix will be added to the name'
    required: false
    default: feelpp
  key:
    description: 'feelpp bintray key'
    required: false
    default: https://bintray.com/user/downloadSubjectPublicKey?username=bintray
  install:
    description: "install feelpp packages"
    required: false
    default: 'libfeelpp1 libfeelpp-dev feelpp-tools'
runs:
  using: "composite"
  steps:
    - name: import repository keys
      run: |
        if [ ! -z "${{ inputs.keys }}" ]; then
            if [ "$(id --user)" -eq "0" ]; then
              sudocmd=""
            else
              sudocmd="sudo"
            fi
        
            $sudocmd apt update || true
            $sudocmd apt install --assume-yes dirmngr
            $sudocmd apt-key adv --keyserver ${{ inputs.key-server }} --recv-keys ${{ inputs.keys }}
        else
            echo "no keys specified, nothing to import"
        fi
      shell: bash
    - name: add debian repo
      run: |
        if [ "$(id --user)" -eq "0" ]; then
          sudocmd=""
        else
          sudocmd="sudo"
        fi
        
        echo "${{ inputs.repo }}" | $sudocmd tee /etc/apt/sources.list.d/${{ inputs.repo-name }}.list
      shell: bash
    - name: install feelpp
      run: |
          if [ "$(id --user)" -eq "0" ]; then
            sudocmd=""
          else
            sudocmd="sudo"
          fi
            
          $sudocmd apt update
          $sudocmd apt install --reinstall ${{ inputs.install }}
      shell: bash
