name: ci
on: [push, pull_request]
jobs:
  linux_container:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: debian, codename: buster, image_owner: , package_type: deb}
          - {os: ubuntu, codename: bionic, image_owner: , package_type: deb}
          - {os: ubuntu, codename: focal, image_owner: , package_type: deb}
    runs-on: ubuntu-latest
    container: ${{ matrix.image_owner }}${{ matrix.os }}:${{ matrix.codename }}
    name: linux container - ${{ matrix.image_owner }}${{ matrix.os }}:${{ matrix.codename }}
    steps:
      - name: install feelpp repo
        uses: feelpp/action-install-feelpp@main
        with:
          dist: ${{ matrix.os }} 
          flavor: ${{ matrix.codename }} 
  linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu, codename: bionic, version: 18.04, image_owner: , package_type: deb}
          - {os: ubuntu, codename: focal, version: 20.04, image_owner: , package_type: deb}
    runs-on: ${{ matrix.os }}-${{ matrix.version }}
    steps:
      - name: add feelpp deb repo
        uses: feelpp/action-install-feelpp@main
        with:
          dist: ${{ matrix.os }} 
          flavor: ${{ matrix.codename }} 
      - name: apt update
        run: sudo apt update
